# Generated by Django 3.1.6 on 2021-02-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='full_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
