# Generated by Django 3.1.6 on 2021-02-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filler', '0002_auto_20210218_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolishDays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
