# Generated by Django 3.1.6 on 2021-03-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filler', '0005_remove_presencesymbol_shortcut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
