# Generated by Django 3.1.6 on 2021-03-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210308_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncategory',
            options={'verbose_name': 'Lesson category', 'verbose_name_plural': 'Lesson categories'},
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.lessoncategory'),
        ),
    ]
