archive_desktop_path: C:\Users\Piotrek\Desktop\teams_archive\
coverted_files_path: D:\Projekty\Python\wku_django\filler\static\files\converted\
raw_teams_file_path: D:\Projekty\Python\wku_django\media\teams\
